### ISSUE TITLE
[Feature] Number of players online

### ISSUE THREAD

**Issue by Bloodlex** [MCSManager/MCSManager#1371] opened 2024-09-11 14:22 UTC
### Description

I'd like to see a number of players online in Minecraft server for each instance.

### Reason

It would be a nice feature to know how many players are online at the moment.

**Comment by Bluemangoo** [comment] 2024-09-12 00:22
Duplicate of #1228

**Comment by SkyKingPX** [comment] 2024-12-23 10:03
This is already in MCSM. You have to set the Minecraft Player Query to the port that your server runs on and it will show you the players of this instance

**Comment by YuMao233** [comment] 2024-12-24 07:46
This is already in MCSManager

**Closed by YuMao233** 2024-12-24 07:46 UTC
Labels: Feature Request
